# Generated by Django 3.2.16 on 2025-02-28 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20250301_0024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseModel',
        ),
    ]
